export const ACCESS_TOKEN_KEY = 'accessToken';

export const PLAYER_POSITION_TYPE_ENUM = {
  ATTACKER: 'ATTACKER',
  DEFENDER: 'DEFENDER',
  MIDFIELDER: 'MIDFIELDER',
  GOALKEEPER: 'GOALKEEPER',
};

export const DEFAULT_TEAM_BUDGET = 5000000;

export const DEFAULT_TEAM_SIZE = {
  [PLAYER_POSITION_TYPE_ENUM.GOALKEEPER]: 3,
  [PLAYER_POSITION_TYPE_ENUM.ATTACKER]: 5,
  [PLAYER_POSITION_TYPE_ENUM.DEFENDER]: 6,
  [PLAYER_POSITION_TYPE_ENUM.MIDFIELDER]: 6,
};

export const TEAM_SIZE = {
  MAX: 25,
  MIN: 15,
};
